/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marcenaria.tela.material;

import marcenaria.material.Chapa;
import marcenaria.pessoa.Layout;
import marcenaria.tela.pessoa.Control;

/**
 * 02/07/2017
 *
 * @author Carlos Eduardo dos Santos Figueiredo
 */
public class TelaChapa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Chapa
     */
    public TelaChapa() {
       if(Chapa.NaoExisteTabelaChapa()){
           Chapa.criadaChapa();
       }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChapa = new javax.swing.JTable();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblComprimento = new javax.swing.JLabel();
        txtComprimento = new javax.swing.JTextField();
        txtLagura = new javax.swing.JTextField();
        lblLargura = new javax.swing.JLabel();
        txtEspessura = new javax.swing.JTextField();
        lblEspessura = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        btnEDIT = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();

        jButton3.setText("ADD");

        setMaximumSize(Layout.getMaximo());
        setMinimumSize(Layout.getMaximo()
        );
        setPreferredSize(Layout.getMaximo()
        );
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbChapa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Produto", "Comprimento", "Largura", "Espessura", "Quantidade", "Preço unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbChapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChapaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbChapaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbChapa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, 497, 102));

        lblFornecedor.setText("Fornecedor:");
        getContentPane().add(lblFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 7, -1, -1));

        txtFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFornecedorMousePressed(evt);
            }
        });
        getContentPane().add(txtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 3, 331, -1));

        lblProduto.setText("Produto: ");
        getContentPane().add(lblProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 157, -1, -1));

        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 153, 195, -1));

        lblComprimento.setText("Comprimento: ");
        getContentPane().add(lblComprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 229, -1, -1));

        txtComprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComprimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtComprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 225, 195, -1));

        txtLagura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLaguraActionPerformed(evt);
            }
        });
        getContentPane().add(txtLagura, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 261, 195, -1));

        lblLargura.setText("Largura: ");
        getContentPane().add(lblLargura, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 265, -1, -1));

        txtEspessura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspessuraActionPerformed(evt);
            }
        });
        getContentPane().add(txtEspessura, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 297, 195, -1));

        lblEspessura.setText("Espessura: ");
        getContentPane().add(lblEspessura, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 301, -1, -1));

        lblPreco.setText("Preço: ");
        getContentPane().add(lblPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 337, -1, -1));

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 333, 195, -1));

        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });
        getContentPane().add(btnADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 369, -1, -1));

        btnDELETE.setText("DELE");
        getContentPane().add(btnDELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 369, -1, -1));

        btnEDIT.setText("EDIT");
        getContentPane().add(btnEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 369, -1, -1));

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 189, 195, -1));

        lblQuantidade.setText("Quantidade: ");
        getContentPane().add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 193, -1, -1));

        setBounds(0, 0, 511, 429);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void txtComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComprimentoActionPerformed

    private void txtLaguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLaguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaguraActionPerformed

    private void txtEspessuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspessuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspessuraActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void tbChapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChapaMouseClicked
        Control.SetarCampo(txtQuantidade, txtProduto, txtComprimento, txtLagura, txtEspessura, txtPreco, tbChapa);
    }//GEN-LAST:event_tbChapaMouseClicked

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed

Chapa.adicionarChapa(Control.deJTextparaInt(txtProduto), Control.deJTextparaDouble(txtComprimento), Control.deJTextparaDouble(txtLagura), Control.deJTextparaDouble(txtEspessura), Control.deJTextparaDouble(txtPreco), txtProduto.getText(),txtFornecedor.getText());

    }//GEN-LAST:event_btnADDActionPerformed

    private void tbChapaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChapaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbChapaMouseReleased

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFornecedorMousePressed
        
    }//GEN-LAST:event_txtFornecedorMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComprimento;
    private javax.swing.JLabel lblEspessura;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTable tbChapa;
    private javax.swing.JTextField txtComprimento;
    private javax.swing.JTextField txtEspessura;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtLagura;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
