/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marcenaria;

import marcenaria.material.Material;
import marcenaria.pessoa.Layout;
import marcenaria.pessoa.Pessoa;
import marcenaria.pessoa.cliente.Projeto;
import marcenaria.tela.material.TelaChapa;
import marcenaria.tela.material.TelaPeca;
import marcenaria.tela.material.TelaPedaco;
import marcenaria.tela.pessoa.TelaCliente;
import marcenaria.tela.pessoa.TelaFornecedor;

/**
 *
 * @author Carlos
 */
public class Marcenaria extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    static TelaCliente tc = new TelaCliente();
    static TelaFornecedor tf = new TelaFornecedor();
    static TelaChapa tcp = new TelaChapa();
    static TelaPeca tpc = new TelaPeca();
    static TelaPedaco tpd = new TelaPedaco();

    /**
     * Creates new form Marcenaria
     */
    public Marcenaria() {

        initComponents();
        Layout.setMaximo(dpMarcenaria.getMaximumSize());
        Layout.setMinimo(dpMarcenaria.getMinimumSize());
        Layout.setPerfil(dpMarcenaria.getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMarcenaria = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCliente = new javax.swing.JMenuItem();
        miFornecedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miProdChapa = new javax.swing.JMenuItem();
        miPeca = new javax.swing.JMenuItem();
        miPedaco = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miLimpaBanco = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout dpMarcenariaLayout = new javax.swing.GroupLayout(dpMarcenaria);
        dpMarcenaria.setLayout(dpMarcenariaLayout);
        dpMarcenariaLayout.setHorizontalGroup(
            dpMarcenariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dpMarcenariaLayout.setVerticalGroup(
            dpMarcenariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miCliente);

        miFornecedor.setText("Fornecedor");
        miFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(miFornecedor);

        jMenu3.setText("Produto");

        miProdChapa.setText("Chapa");
        miProdChapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProdChapaActionPerformed(evt);
            }
        });
        jMenu3.add(miProdChapa);

        miPeca.setText("Peça");
        miPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPecaActionPerformed(evt);
            }
        });
        jMenu3.add(miPeca);

        miPedaco.setText("Pedaço");
        miPedaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPedacoActionPerformed(evt);
            }
        });
        jMenu3.add(miPedaco);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        miLimpaBanco.setText("Limpa Banco");
        miLimpaBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLimpaBancoActionPerformed(evt);
            }
        });
        jMenu2.add(miLimpaBanco);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpMarcenaria)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpMarcenaria)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        fechareAbre(tc);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFornecedorActionPerformed
        fechareAbre(tf);
    }//GEN-LAST:event_miFornecedorActionPerformed

    private void miLimpaBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLimpaBancoActionPerformed
        Pessoa.deletarPessoa();
        Material.deletarMaterial();
        Projeto.deletarProjeto();
    }//GEN-LAST:event_miLimpaBancoActionPerformed

    private void miProdChapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProdChapaActionPerformed
        fechareAbre(tcp);
    }//GEN-LAST:event_miProdChapaActionPerformed

    private void miPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPecaActionPerformed
       fechareAbre(tpc);
    }//GEN-LAST:event_miPecaActionPerformed

    private void miPedacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPedacoActionPerformed
        fechareAbre(tpd);
    }//GEN-LAST:event_miPedacoActionPerformed
    public void fechareAbre(Object o) {
        if (o.equals(tc)) {
            tf.dispose();
            tcp.dispose();
            tpc.dispose();
            tpd.dispose();
            tc.setVisible(true);
            dpMarcenaria.add(tc);
        } else if (o.equals(tf)) {
            tc.dispose();
            tcp.dispose();
            tpc.dispose();
            tpd.dispose();
            tf.setVisible(true);
            dpMarcenaria.add(tf);
        } else if (o.equals(tcp)) {
            tf.dispose();
            tc.dispose();
            tpc.dispose();
            tpd.dispose();
            tcp.setVisible(true);
            dpMarcenaria.add(tcp);
        } else if (o.equals(tpc)) {
            tf.dispose();
            tcp.dispose();
            tc.dispose();
            tpd.dispose();
            tpc.setVisible(true);
            dpMarcenaria.add(tpc);
        } else if (o.equals(tpd)) {
            tf.dispose();
            tcp.dispose();
            tpc.dispose();
            tc.dispose();
            tpd.setVisible(true);
            dpMarcenaria.add(tpd);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcenaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcenaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcenaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcenaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Marcenaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpMarcenaria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miFornecedor;
    private javax.swing.JMenuItem miLimpaBanco;
    private javax.swing.JMenuItem miPeca;
    private javax.swing.JMenuItem miPedaco;
    private javax.swing.JMenuItem miProdChapa;
    // End of variables declaration//GEN-END:variables

}
