/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author carlos
 */
public class Compensado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Compensado
     */
    public Compensado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRazaoSocial = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblRazaoSocial2 = new javax.swing.JLabel();
        lblRazaoSocial3 = new javax.swing.JLabel();
        lblRazaoSocial4 = new javax.swing.JLabel();
        lblRazaoSocial5 = new javax.swing.JLabel();
        txtRazao5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        cbComprimento = new javax.swing.JComboBox<>();
        cbEspessura = new javax.swing.JComboBox<>();
        lblCM = new javax.swing.JLabel();
        lblCM1 = new javax.swing.JLabel();
        lblCM2 = new javax.swing.JLabel();

        setTitle("Compensado");

        lblRazaoSocial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRazaoSocial.setText("Razão Social:");

        txtRazao.setEditable(false);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblRazaoSocial2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRazaoSocial2.setText("Largura:");

        lblRazaoSocial3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRazaoSocial3.setText("Comprimento:");

        lblRazaoSocial4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRazaoSocial4.setText("Espessura:");

        lblRazaoSocial5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRazaoSocial5.setText("Preço:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "160" }));

        cbComprimento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbComprimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "220 " }));

        cbEspessura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbEspessura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "04", "06", "10", "15", "18" }));
        cbEspessura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspessuraActionPerformed(evt);
            }
        });

        lblCM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCM.setText("CM");

        lblCM1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCM1.setText("CM");

        lblCM2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCM2.setText("MM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazaoSocial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRazaoSocial2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRazaoSocial3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRazaoSocial4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRazaoSocial5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRazao)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtRazao5, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbEspessura, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbComprimento, javax.swing.GroupLayout.Alignment.LEADING, 0, 83, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCM)
                            .addComponent(lblCM1)
                            .addComponent(lblCM2))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazaoSocial3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCM1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial4)
                    .addComponent(cbEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial5)
                    .addComponent(txtRazao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEspessuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspessuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspessuraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbComprimento;
    private javax.swing.JComboBox<String> cbEspessura;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblCM;
    private javax.swing.JLabel lblCM1;
    private javax.swing.JLabel lblCM2;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRazaoSocial2;
    private javax.swing.JLabel lblRazaoSocial3;
    private javax.swing.JLabel lblRazaoSocial4;
    private javax.swing.JLabel lblRazaoSocial5;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtRazao5;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
