/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author carlos
 */
public class PedacoCompensado extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedacoCompensado
     */
    public PedacoCompensado() {
        initComponents();
    }
 public void tabela(){ 
    
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedacoCompensado = new javax.swing.JTable();
        lblQuantidade = new javax.swing.JLabel();
        lblComprimento = new javax.swing.JLabel();
        lblLargura = new javax.swing.JLabel();
        lblEspessura = new javax.swing.JLabel();
        cbEspessura = new javax.swing.JComboBox<>();
        txtQuantidade = new javax.swing.JTextField();
        txtComprimento = new javax.swing.JTextField();
        txtLargura = new javax.swing.JTextField();
        btEditarPeca = new javax.swing.JButton();
        btAdicionarPeca = new javax.swing.JButton();
        btReservarPeca = new javax.swing.JButton();
        btDeletarPeca = new javax.swing.JButton();
        btInformacaoPeca = new javax.swing.JButton();

        tbPedacoCompensado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPedacoCompensado);

        lblQuantidade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        lblComprimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblComprimento.setText("Comprimento:");

        lblLargura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLargura.setText("Largura:");

        lblEspessura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEspessura.setText("Espessura:");

        cbEspessura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbEspessura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEspessura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspessuraActionPerformed(evt);
            }
        });

        txtQuantidade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        txtComprimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtLargura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLarguraActionPerformed(evt);
            }
        });

        btEditarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/controle/if_document_text_edit_103514.png"))); // NOI18N
        btEditarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarPecaActionPerformed(evt);
            }
        });

        btAdicionarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/controle/if_document_text_add_103511.png"))); // NOI18N
        btAdicionarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarPecaActionPerformed(evt);
            }
        });

        btReservarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/controle/if_document_text_accept_103510.png"))); // NOI18N
        btReservarPeca.setToolTipText("Reservar");
        btReservarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservarPecaActionPerformed(evt);
            }
        });

        btDeletarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/controle/if_document_text_cancel_103512.png"))); // NOI18N
        btDeletarPeca.setToolTipText("Excluir");
        btDeletarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarPecaActionPerformed(evt);
            }
        });

        btInformacaoPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/controle/if_document_text_information_103515.png"))); // NOI18N
        btInformacaoPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformacaoPecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLargura)
                            .addComponent(lblEspessura)
                            .addComponent(lblComprimento)
                            .addComponent(lblQuantidade))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuantidade)
                                        .addComponent(txtComprimento, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbEspessura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btAdicionarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEditarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btReservarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDeletarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btInformacaoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblQuantidade)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblComprimento)
                                    .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblLargura)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEspessura)
                            .addComponent(cbEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAdicionarPeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btEditarPeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btInformacaoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btDeletarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btReservarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEspessuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspessuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspessuraActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLarguraActionPerformed

    private void btEditarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarPecaActionPerformed

    private void btDeletarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeletarPecaActionPerformed

    private void btReservarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservarPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btReservarPecaActionPerformed

    private void btAdicionarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarPecaActionPerformed

    private void btInformacaoPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformacaoPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInformacaoPecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarPeca;
    private javax.swing.JButton btDeletarPeca;
    private javax.swing.JButton btEditarPeca;
    private javax.swing.JButton btInformacaoPeca;
    private javax.swing.JButton btReservarPeca;
    private javax.swing.JComboBox<String> cbEspessura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComprimento;
    private javax.swing.JLabel lblEspessura;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTable tbPedacoCompensado;
    private javax.swing.JTextField txtComprimento;
    private javax.swing.JTextField txtLargura;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
