/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author carlos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miCadastroEmpresa = new javax.swing.JMenuItem();
        miCadastroFuncionario = new javax.swing.JMenuItem();
        miCadastroProduto = new javax.swing.JMenuItem();
        miCadastroCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miCompensado = new javax.swing.JMenuItem();
        miMDF = new javax.swing.JMenuItem();
        mLogin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        mCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_ic_playlist_add_48px_352076 (2).png"))); // NOI18N
        mCadastro.setText("Cadastro");
        mCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroActionPerformed(evt);
            }
        });

        miCadastroEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miCadastroEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_23_3229640.png"))); // NOI18N
        miCadastroEmpresa.setText("Empresa");
        miCadastroEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEmpresaActionPerformed(evt);
            }
        });
        mCadastro.add(miCadastroEmpresa);

        miCadastroFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        miCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_icon-person_211874.png"))); // NOI18N
        miCadastroFuncionario.setText("Funcionario");
        miCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroFuncionarioActionPerformed(evt);
            }
        });
        mCadastro.add(miCadastroFuncionario);

        miCadastroProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_17_3229634.png"))); // NOI18N
        miCadastroProduto.setText("Produto");
        miCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroProdutoActionPerformed(evt);
            }
        });
        mCadastro.add(miCadastroProduto);

        miCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        miCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_icon-person_211874.png"))); // NOI18N
        miCadastroCliente.setText("Cliente");
        miCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroClienteActionPerformed(evt);
            }
        });
        mCadastro.add(miCadastroCliente);

        jMenuBar1.add(mCadastro);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_icon-social-buffer_211894.png"))); // NOI18N
        jMenu3.setText("Obter");

        miCompensado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_icon-social-buffer_211894.png"))); // NOI18N
        miCompensado.setText("Compensado");
        miCompensado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompensadoActionPerformed(evt);
            }
        });
        jMenu3.add(miCompensado);

        miMDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/layout/if_icon-social-buffer_211894.png"))); // NOI18N
        miMDF.setText("MDF");
        jMenu3.add(miMDF);

        jMenuBar1.add(jMenu3);

        mLogin.setText("Login");
        mLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginActionPerformed(evt);
            }
        });
        jMenuBar1.add(mLogin);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("Só chapa e Pedaço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEmpresaActionPerformed
        // Chama a Tela de Empresa
        TelaEmpresa te = new TelaEmpresa();
        te.setVisible(true);
        Desktop.add(te);
    }//GEN-LAST:event_miCadastroEmpresaActionPerformed

    private void miCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroFuncionarioActionPerformed
        // Chama a Tela de Funcionario
        TelaFuncionario tp = new TelaFuncionario();
        tp.setVisible(true);
        Desktop.add(tp);
    }//GEN-LAST:event_miCadastroFuncionarioActionPerformed

    private void miCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroProdutoActionPerformed
        // Chama a Tela de Produto
        TelaProduto tpr = new TelaProduto();
        tpr.setVisible(true);
        Desktop.add(tpr);
    }//GEN-LAST:event_miCadastroProdutoActionPerformed

    private void miCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroClienteActionPerformed
        // Chama a tela cliente
        TelaCliente tc = new TelaCliente();
        tc.setVisible(true);
        Desktop.add(tc);
    }//GEN-LAST:event_miCadastroClienteActionPerformed

    private void mCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCadastroActionPerformed

    private void mLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginActionPerformed
        // Chama a Tela de Login
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        Desktop.add(tl);
    }//GEN-LAST:event_mLoginActionPerformed

    private void miCompensadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompensadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCompensadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mLogin;
    private javax.swing.JMenuItem miCadastroCliente;
    private javax.swing.JMenuItem miCadastroEmpresa;
    private javax.swing.JMenuItem miCadastroFuncionario;
    private javax.swing.JMenuItem miCadastroProduto;
    private javax.swing.JMenuItem miCompensado;
    private javax.swing.JMenuItem miMDF;
    // End of variables declaration//GEN-END:variables
}
