/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Carlos
 */
public class Gaveteiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gaveteiro
     */
    public Gaveteiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDArmario = new javax.swing.JLabel();
        txtIDArmario = new javax.swing.JTextField();
        lblIDGaveteiro = new javax.swing.JLabel();
        txtIDGaveteiro = new javax.swing.JTextField();
        lblQuantidadeGaveteiro = new javax.swing.JLabel();
        txtQuantidadeGaveteiro = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lblEspessura = new javax.swing.JLabel();
        txtEspessura = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblComprimento = new javax.swing.JLabel();
        txtComprimento = new javax.swing.JTextField();
        lblLargura = new javax.swing.JLabel();
        txtLargura = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gaveteiro");
        setToolTipText("");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        lblIDArmario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIDArmario.setText("Identificação  do armario:");
        lblIDArmario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblIDArmario.setPreferredSize(new java.awt.Dimension(41, 24));

        txtIDArmario.setEditable(false);
        txtIDArmario.setMinimumSize(new java.awt.Dimension(14, 15));

        lblIDGaveteiro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIDGaveteiro.setText("Identificação do gaveteiro:");
        lblIDGaveteiro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblIDGaveteiro.setPreferredSize(new java.awt.Dimension(41, 15));

        txtIDGaveteiro.setMinimumSize(new java.awt.Dimension(14, 15));

        lblQuantidadeGaveteiro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblQuantidadeGaveteiro.setText("Quantidade de Gaveteiro:");
        lblQuantidadeGaveteiro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblQuantidadeGaveteiro.setPreferredSize(new java.awt.Dimension(41, 15));

        txtQuantidadeGaveteiro.setMinimumSize(new java.awt.Dimension(14, 15));

        lblAltura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAltura.setText("Altura:");
        lblAltura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblAltura.setPreferredSize(new java.awt.Dimension(41, 15));

        txtAltura.setMinimumSize(new java.awt.Dimension(14, 15));

        lblEspessura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEspessura.setText("Espessura:");
        lblEspessura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblEspessura.setPreferredSize(new java.awt.Dimension(41, 15));

        txtEspessura.setMinimumSize(new java.awt.Dimension(14, 15));

        lblDescricao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDescricao.setText("Descrição:");
        lblDescricao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblDescricao.setPreferredSize(new java.awt.Dimension(41, 15));

        txtDescricao.setMinimumSize(new java.awt.Dimension(14, 15));

        lblComprimento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblComprimento.setText("Comprimento:");
        lblComprimento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblComprimento.setPreferredSize(new java.awt.Dimension(41, 15));

        txtComprimento.setMinimumSize(new java.awt.Dimension(14, 15));

        lblLargura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLargura.setText("Largura:");
        lblLargura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblLargura.setPreferredSize(new java.awt.Dimension(41, 15));

        txtLargura.setMinimumSize(new java.awt.Dimension(14, 15));

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdicionar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIDArmario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIDGaveteiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEspessura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblQuantidadeGaveteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblLargura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidadeGaveteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEspessura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtIDGaveteiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addComponent(txtIDArmario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 46, Short.MAX_VALUE))
                            .addComponent(txtComprimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblIDGaveteiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIDGaveteiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeGaveteiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeGaveteiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAdicionar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed

        view.Gaveta gaveta = new Gaveta();
        if (!gaveta.isVisible()) {
            gaveta.setVisible(true);
            TelaPrincipal.AreadeTrabalho.add(gaveta);
            dispose();
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblComprimento;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEspessura;
    private javax.swing.JLabel lblIDArmario;
    private javax.swing.JLabel lblIDGaveteiro;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblQuantidadeGaveteiro;
    public javax.swing.JTextField txtAltura;
    public javax.swing.JTextField txtComprimento;
    public javax.swing.JTextField txtDescricao;
    public javax.swing.JTextField txtEspessura;
    public javax.swing.JTextField txtIDArmario;
    public javax.swing.JTextField txtIDGaveteiro;
    public javax.swing.JTextField txtLargura;
    public javax.swing.JTextField txtQuantidadeGaveteiro;
    // End of variables declaration//GEN-END:variables
}
