/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Carlos
 */
public class Gaveta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gaveta
     */
    public Gaveta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuantidadedeGaveta = new javax.swing.JLabel();
        txtQuantidadedeGaveta = new javax.swing.JTextField();

        setClosable(true);

        lblQuantidadedeGaveta.setText("Quantidade de Gaveta:");

        txtQuantidadedeGaveta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadedeGavetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblQuantidadedeGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadedeGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadedeGaveta)
                    .addComponent(txtQuantidadedeGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        lblQuantidadedeGaveta.getAccessibleContext().setAccessibleName("Quantidade de Gaveta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantidadedeGavetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadedeGavetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadedeGavetaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblQuantidadedeGaveta;
    private javax.swing.JTextField txtQuantidadedeGaveta;
    // End of variables declaration//GEN-END:variables
}
