/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Carlos
 */
public class Lateral extends javax.swing.JInternalFrame {

    /**
     * Creates new form Lateral
     */
    public Lateral() {
        initComponents();
        txtIdArmario.setText(view.TelaPrincipal.getM().txtIDArmario.getText());
        txtAlturaLateral.setText(view.TelaPrincipal.getM().txtAltura.getText());
        txtBaseLateral.setText(view.TelaPrincipal.getM().txtLargura.getText());
        txtEspessuraLateral.setText(view.TelaPrincipal.getM().txtEspessura.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotao = new javax.swing.ButtonGroup();
        lblIdArmario = new javax.swing.JLabel();
        txtIdArmario = new javax.swing.JTextField();
        txtQuantidadeLateral = new javax.swing.JTextField();
        lblQuantidadeLateral = new javax.swing.JLabel();
        lblAlturaLateral = new javax.swing.JLabel();
        txtAlturaLateral = new javax.swing.JTextField();
        txtBaseLateral = new javax.swing.JTextField();
        lblBaseLateral = new javax.swing.JLabel();
        lblEspessuraLateral = new javax.swing.JLabel();
        txtEspessuraLateral = new javax.swing.JTextField();
        lblVirarLateral = new javax.swing.JLabel();
        txtQuantidadeLateral6 = new javax.swing.JTextField();
        lblQuantidadeLateral6 = new javax.swing.JLabel();
        txtIDLateral = new javax.swing.JTextField();
        lblIDLateral = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnNAO = new javax.swing.JRadioButton();
        btnSIM = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Lateral");
        setToolTipText("");

        lblIdArmario.setText("ID do Armario:");
        lblIdArmario.setToolTipText("");

        txtIdArmario.setToolTipText("");

        txtQuantidadeLateral.setToolTipText("");
        txtQuantidadeLateral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeLateralKeyPressed(evt);
            }
        });

        lblQuantidadeLateral.setText("Quantidade  de Lateral:");

        lblAlturaLateral.setText("Altura do Lateral:");

        txtAlturaLateral.setToolTipText("");

        txtBaseLateral.setToolTipText("");

        lblBaseLateral.setText("Base  de Lateral:");

        lblEspessuraLateral.setText("Espessura  de Lateral:");

        txtEspessuraLateral.setToolTipText("");

        lblVirarLateral.setText("Pode vira o Lateral:");

        txtQuantidadeLateral6.setToolTipText("");

        lblQuantidadeLateral6.setText("Quantidade  de Lateral:");

        txtIDLateral.setToolTipText("");

        lblIDLateral.setText("ID  de Lateral:");

        btnAdicionar.setText("Adicionar");

        GrupoBotao.add(btnNAO);
        btnNAO.setSelected(true);
        btnNAO.setText("Não");

        GrupoBotao.add(btnSIM);
        btnSIM.setText("Sim");
        btnSIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArmario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuantidadeLateral, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlturaLateral, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBaseLateral, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEspessuraLateral, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVirarLateral, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuantidadeLateral6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlturaLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtBaseLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtEspessuraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtQuantidadeLateral6, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtQuantidadeLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdArmario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIDLateral)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSIM, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNAO, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAdicionar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArmario)
                    .addComponent(txtIdArmario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIDLateral)
                        .addComponent(txtIDLateral)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeLateral)
                    .addComponent(txtQuantidadeLateral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlturaLateral)
                    .addComponent(txtAlturaLateral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBaseLateral)
                    .addComponent(txtBaseLateral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspessuraLateral)
                    .addComponent(txtEspessuraLateral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVirarLateral)
                    .addComponent(btnNAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeLateral6)
                    .addComponent(txtQuantidadeLateral6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnAdicionar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSIMActionPerformed

    private void txtQuantidadeLateralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeLateralKeyPressed
        if (Integer.valueOf(txtQuantidadeLateral.getText()) > 1) {
            lblVirarLateral.setText("Pode vira os Laterais:");
        } else {
            lblVirarLateral.setText("Pode vira o Lateral:");
        }
    }//GEN-LAST:event_txtQuantidadeLateralKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotao;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JRadioButton btnNAO;
    private javax.swing.JRadioButton btnSIM;
    private javax.swing.JLabel lblAlturaLateral;
    private javax.swing.JLabel lblBaseLateral;
    private javax.swing.JLabel lblEspessuraLateral;
    private javax.swing.JLabel lblIDLateral;
    private javax.swing.JLabel lblIdArmario;
    private javax.swing.JLabel lblQuantidadeLateral;
    private javax.swing.JLabel lblQuantidadeLateral6;
    private javax.swing.JLabel lblVirarLateral;
    private javax.swing.JTextField txtAlturaLateral;
    private javax.swing.JTextField txtBaseLateral;
    private javax.swing.JTextField txtEspessuraLateral;
    private javax.swing.JTextField txtIDLateral;
    private javax.swing.JTextField txtIdArmario;
    private javax.swing.JTextField txtQuantidadeLateral;
    private javax.swing.JTextField txtQuantidadeLateral6;
    // End of variables declaration//GEN-END:variables
}
