/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Carlos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static Movel m;

    public static Movel getM() {
        m.setName("casa");
        return m;
    }

    public static void setM(Movel m) {
        TelaPrincipal.m = m;
    }

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        m = new Movel();
        control.Movel.temp(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        AreadeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuNovo = new javax.swing.JMenu();
        novoMovel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setSize(new java.awt.Dimension(500, 400));
        setType(java.awt.Window.Type.UTILITY);

        AreadeTrabalho.setBackground(new java.awt.Color(51, 51, 255));
        AreadeTrabalho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AreadeTrabalho.setForeground(new java.awt.Color(0, 102, 102));
        AreadeTrabalho.setAlignmentX(0.0F);
        AreadeTrabalho.setAlignmentY(0.0F);
        AreadeTrabalho.setAutoscrolls(true);
        AreadeTrabalho.setMaximumSize(new java.awt.Dimension(450, 300));
        AreadeTrabalho.setMinimumSize(new java.awt.Dimension(445, 300));
        AreadeTrabalho.setName(""); // NOI18N
        AreadeTrabalho.setLayout(new java.awt.BorderLayout());

        menuNovo.setText("Novo");
        menuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNovoMouseClicked(evt);
            }
        });

        novoMovel.setText("Novo Movel");
        novoMovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoMovelMouseClicked(evt);
            }
        });
        novoMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMovelActionPerformed(evt);
            }
        });
        menuNovo.add(novoMovel);

        jMenuBar1.add(menuNovo);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreadeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreadeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNovoMouseClicked

    }//GEN-LAST:event_menuNovoMouseClicked

    private void novoMovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoMovelMouseClicked
        /**
         * if (!m.isVisible()) { m.setVisible(true); AreadeTrabalho.add(m); }*
         */
    }//GEN-LAST:event_novoMovelMouseClicked

    private void novoMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMovelActionPerformed
        if (!m.isVisible()) {
            m.setVisible(true);
            AreadeTrabalho.add(m);
        }
    }//GEN-LAST:event_novoMovelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane AreadeTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuNovo;
    private javax.swing.JMenuItem novoMovel;
    // End of variables declaration//GEN-END:variables
}
